
package gui.View;

import com.formdev.flatlaf.FlatDarkLaf;
import gui.Main;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import gui.Service.UserService;
import gui.Service.TaxCalculator;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LAPTOP
 */
public class viewTax extends javax.swing.JPanel {
    private UserService userService;

    /**
     * Creates new form viewTax
     */
    public viewTax() {
        initComponents();
        FlatDarkLaf.setup();
        userService = new UserService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 177, 79));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Check your tax");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextField1.setOpaque(true);
        jTextField1.setPreferredSize(new java.awt.Dimension(71, 50));
        jTextField1.setSelectedTextColor(new java.awt.Color(0, 177, 79));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Confirm");
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.setOpaque(true);
        jButton1.setPreferredSize(new java.awt.Dimension(75, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Enter ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String staffIdText = jTextField1.getText().trim();
        if (staffIdText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your ID.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        long staffId;
        try {
            staffId = Long.parseLong(staffIdText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID must be a number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra sự tồn tại của user_id
        
        try {
            boolean staffExists = userService.isStaffExists(staffId);
            if (!staffExists) {
            JOptionPane.showMessageDialog(this, "ID invalid.", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        } catch (ClassNotFoundException |SQLException e) {  
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);  
        }  
        
        // Lấy grossIncome từ Income_Details
        long grossIncome = 0;
        try {
            grossIncome = userService.getGrossIncome(staffId);
            if (grossIncome <= 0) {
            JOptionPane.showMessageDialog(this, "This user's income was not detected.", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        } catch (ClassNotFoundException |SQLException e) {  
        JOptionPane.showMessageDialog(this, "error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);  
        }  
        
        
        
        // Tạo TaxCalculator với grossIncome
        TaxCalculator taxCalculator = new TaxCalculator(grossIncome, (int) staffId);

        // Cập nhật TaxDetails với taxCalculator
        TaxDetails taxDetails = getTaxDetailsPanel();
        try {
            taxDetails.updateTaxDetails(taxCalculator);
        } catch (ClassNotFoundException |SQLException e) {  
        JOptionPane.showMessageDialog(this, "error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);  
        }  

        // Chuyển sang TaxDetails
        CardLayout cardLayout = (CardLayout) this.getParent().getLayout();
        cardLayout.show(this.getParent(), "taxCard");
    }//GEN-LAST:event_jButton1ActionPerformed
    private TaxDetails getTaxDetailsPanel() {
        // Giả sử Main là parent của viewTax
        Main mainFrame = (Main) javax.swing.SwingUtilities.getWindowAncestor(this);
        return mainFrame.getTaxDetails();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
